# Generated by Django 3.2.5 on 2021-07-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=600)),
                ('horario', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('usuario', models.CharField(blank=True, max_length=600, null=True, unique=True)),
                ('correo', models.CharField(blank=True, max_length=600, null=True, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=600)),
                ('a_paterno', models.CharField(max_length=600)),
                ('a_materno', models.CharField(blank=True, max_length=600, null=True)),
                ('edad', models.IntegerField(blank=True, default=1, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_clase', to='Academia.clase')),
            ],
        ),
    ]
